uco-core/core.ttl, uco-observable/observable.ttl, uco-types/types.ttl
Moved the existing observable:HashNameEnum datatype definition to core.ttl as core:HashNameEnum to allow it to be used as a range within types.ttl without adding any more unecessary imports.
Removed observable:HashNameEnum.
Modified range of types:hashMethod to be core:HashNameEnum.
=> Modifications to address issue #95

uco-core/core.ttl
Modified core:confidence from ObjectProperty to DatatypeProperty
Modified range of core:confidence from core:ControlledVocabulary to be xsd:nonNegativeInteger with maxInclusive restriction of 100
Modified the owl:onClass for the restriciton of core:confidence on core:Confidence to utilize xsd:nonNegativeInteger rather than core:ControlledVocabulary
=> Modifications to address issue #101

uco-core/core.ttl, uco-investigation/investigation.ttl
Added the missing range definition of xsd:dateTime to core:startTime (this was fixing a bug)
Added core:endTime and core:startTime as optional properties on investigation:Authorization
=> Modifications to address issue #63

uco-action/action.ttl, uco-observable/observable.ttl, uco-types/types.ttl
observables.ttl
Removed ArrayOfHash, ArrayOfObject and ArrayOfString classes
Removed types:hash property
Removed types:object property
Removed ArrayOfString from domain of types:value property
action.ttl
Modified action:ArrayOfAction to locally define it as a list of action:action specifically rather than as a subclass of types:ArrayOfObject
Added action:action object to convey a single Action as part of an ArrayOfAction
observable.ttl
Modified range of observable:hashes to be types:Hash rather than types:ArrayOfHash
Modified range of observable:message to be observable:CyberIterm rather than ArrayOfObject
Modified owl:onDataRange of observable:message property restriction on the observable:MessageThread class to by observable:CyberItem
=> Modifications to address issue #114

uco-observable/observable.ttl
The prefix was replaced and the rdf-toolkit used to normalize the file.
=> Address Issue 135 - Put observable prefix back into observable.ttl

uco-observable/observable.ttl
This patch implements the Change Proposal attached to Issue 160, except
for providing migration guidance for prior adopters of the property.
https://github.com/ucoProject/UCO/issues/160
=> Revise range of observable:partitionID to be string

uco-core/editor_annotation.ttl
This fixes a syntax error confirms the fix by running that ontology file through rdf-toolkit.
=> Fix syntax error in editor_annotation.ttl

uco-action/action.ttl, uco-core/core.ttl, uco-master/uco.ttl, uco-observable/observable.ttl
These issues were discovered by running `make check` in this directory
of the CASE-Examples-QC repository (at the current `master` head):
https://github.com/ajnelson-nist/CASE-Examples-QC/tree/c07ca3b6906f1791f4782c02c13b606f8b5729c6/tests/UCO
The command used is documented in the Makefile `src/normalize-ontology.mk`:
java -jar $(top_srcdir)/lib/rdf-toolkit.jar \
--infer-base-iri \
--inline-blank-nodes \
--source $< \
--source-format turtle \
--target $@_ \
--target-format turtle
Please note this disclaimer related to mention of specific software:
Participation by NIST in the creation of the instructions to this
toolkit is not intended to imply a recommendation or endorsement by the
National Institute of Standards and Technology, nor is it intended to
imply that any specific software or …
=> Apply normalization with rdf-toolkit

uco-core/core-da.ttl, uco-core/core.ttl, uco-master/uco.ttl, uco-observable/observable-da.ttl, uco-observable/observable.ttl, uco-types/types.ttl, uco-vocabulary/vocabulary.ttl
This patch applies rdf-toolkit to all of the Turtle files in UCO
(including *-da.ttl files), following the normalization process adopted
by the CASE community.
Normalization was confirmed by the CASE-Examples-QC repository.
Please note this disclaimer related to mention of specific software:
Participation by NIST in the creation of the instructions to this
toolkit is not intended to imply a recommendation or endorsement by the
National Institute of Standards and Technology, nor is it intended to
imply that any specific software or toolkit is necessarily the best
available for the purpose.
References:
* [CASE-Examples-QC] https://github.com/ajnelson-nist/CASE-Examples-QC
Branch: OC-43
* [CASE ONT-5] (CP-3) Establish ontology normalization procedure
* [Normalization process] …
=> Normalize content with rdf-toolkit

uco-core/core-da.ttl
References should have been removed in UCO 0.5.0.
References:
* [OC-83] (CP-31) core-da.ttl includes errant assertion on investigation
namespace
* [UCO 209] https://github.com/ucoProject/UCO/issues/209
=> Bug fix cp31

uco-action/action.ttl, uco-core/core-da.ttl, uco-core/core.ttl, uco-master/uco.ttl, uco-types/types.ttl
This patch bumps the version declaration of UCO to 0.6.0.  It also
removes some unmaintained versionInfo declarations from other
ontologies.  There is a plan to restore these other versionInfo
declarations in CASE CP-17, but CASE and UCO are currently analyzing
options for the version-incrementing strategy.
This patch is confirmed to not cause normalization issues.
References:
* [CASE-Examples-QC] https://github.com/ajnelson-nist/CASE-Examples-QC
* [CASE ONT-64] (CP-17) Define scheme for CASE and UCO importable
versioned IRIs
=> Consolidate versionInfo to one declaration of 0.6.0

uco-observable/observable-da.ttl, uco-observable/observable.ttl
References:
* [OC-34] (CP-52) observable:nameserver should be camel-cased
=> Spell observable:nameserver with camel-casing

uco-observable/observable.ttl
The proposal filed in Issue 160 changed the type of partitionID to be a
string instead of an integer.  Unfortunately, one update point was
missed.
(Patch v2: I did not realize that rdf-toolkit also has a "Hidden"
Restriction sort key, by onDataRange before onProperty.  Branch name was
also of incorrect form.)
References:
* [Issue 160] Change Proposal: Revise range and documentation of
partitionID
* [OC-120] (CP-46) DiskPartitionFacet accidentally has partitionID range
as xsd:integer
=> Add missed update for partitionID type

uco-observable/observable-da.ttl, uco-observable/observable.ttl
References:
* [OC-99] (CP-38) NTFSFileSystemFacet describes an NTFS file, not file
system
=> Change NTFSFileSystemFacet to NTFSFileFacet

uco-observable/observable.ttl
Added rdfs:comment: "When used to characterize a file the sizeInBytes property conveys the recorded size of a file in a file system."@en ; to the owl:restriction for observable:sizeInBytes on the observable:FileFacet class in support of CP-54
=> Added an rdfs:comment to support observable:sizeInBytes (CP-54)

Makefile, src/review.mk
This patch is a revision to the implementation of CP-39, to guarantee
the visit order of subdirectories.
While undergoing an in-depth normalization review of each Turtle file
today, I and a person I was working with realized that the visit order
of subdirectories was non-deterministic between Make runs.  On the scale
of nuisances, this is minor, as it causes some confusion on when a
per-file review will be completed, but does not cause any true review
errors because UCO's subdirectories are all independently reviewable.
(The non-determinimism was not apparent in my reviews for the initial
patch because my testing tended to run with full parallelism from
'make -j'.)
Aside from directory and file visit order, no semantic or behavioral
changes are made in this patch.
References:
* [OC-98] …
=> Perform Make directory traversal in sort order

uco-observable/observable-da.ttl
Fixed naming convention of observable:region_end_address within observable-da.ttl. This is in continuation of implementing changes for CP-16.
=> Continuation of CP-16.

uco-observable/observable-da.ttl
This is a continuation of Github Issue 143, originally thought resolved
for UCO 0.4.0.  The casing correction was not applied in the domain
assertions file, which could impact the SHACL conversion of UCO.
This patch has no attached Change Proposal because of its prior approval
under Issue 143.
This was discovered through inspection of UCO with the tool, "ROBOT".
References:
* [Issue 143] Casing correction - "picturetype"
https://github.com/ucoProject/UCO/issues/143
* [OC-68] (CP-23) Convert current property restrictions and domain
assertions to SHACL class shapes
* [ROBOT] R.C. Jackson, J.P. Balhoff, E. Douglass, N.L. Harris, C.J.
Mungall, and J.A. Overton. ROBOT: A tool for automating ontology
workflows. BMC Bioinformatics, vol. 20, July 2019.
Signed-off-by: Alex Nelson …
=> Correct casing of picturetype to pictureType

uco-observable/observable.ttl
Removed 'xsd:string' from two properties within observable:MobileDeviceFacet.
The two properties: observable:mockLocationsAllowed and
observable:phoneActivationTime had two added values from the SHACL conversion.
=> Removed xsd:string according to CP-72

uco-observable/observable.ttl
Extended the range of observable:status to be an owl:unionOf xsd:string,
observable:TaskStatusVocab, and observable:WhoisStatusVocab. Also, removed
the observable:WhoisStatusVocab datatype as a property restriction for
observable:status within observable:ProcessFacet.
=> Implemented CP-73

uco-observable/observable.ttl
Extended the range of observable:priority to be an owl:unoinOf xsd:integer,
xsd:string, and vocabulary:TaskPriorityVocab. Also, removed xsd:string from
being a property restriction for observable:priority within
observable:WindowsTaskFacet and observable:WindowsThreadFacet.
Acked-By: Trevor Bobka <tbobka@mitre.org>
=> Implemented CP-74

uco-observable/observable.ttl
Removed 'xsd:float' from the property restriction of observable:entropy on
the observable:WindowsPESection class.
=> Implemented CP-75

uco-observable/observable.ttl
Removed 'observable:ObservableObject' from the range on observable:owner and
each class that called it as a property restriction.
=> Implemented CP-76

uco-observable/observable.ttl
Added the observable:listedCount property that was excluded in the
implementation of CP-7. Also, ensured the proper SHACL constraints were added
for the its property restriction within observable:TwitterProfileFacet.
=> Implemented CP-78

tests/Makefile, tests/test_uco_monolithic.py
References:
* [OC-165] (CP-79) Several classes have multiple sh:datatypes and are
invalid by SHACL spec
=> Add test for sh:datatype count validity

uco-types/types.ttl
Extended the range of types:entry to include types:DictionaryEntry and
types:ControlledDictionaryEntry. Also, removed types:DictionaryEntry from the
property restriction for types:entry within the types:ControlledDictionary
class.
=> Implemented CP-77

ontology/observable/observable.ttl
References:
* [OC-188] (CP-85) sh:datatype property needs to be removed due to SHACL conversion errors
Signed-off-by: TJ Balon <tbalon@mitre.org>
=> Remove SHACL conversion errors

src/review.mk
This is a follow-on patch to FastTrack-CP-56, which was already merged as part of the UCO 0.8.0 release.  A minor typo is being corrected, not necessitating any revisions to the proposal or website documentation, and hence not requiring any committee action.
=> Fix typo in instructions

ontology/observable/observable.ttl
References:
* [OC-116] (CP-104) observable:mimeType should have unbounded
cardinality to support polyglots
=> Allow unbounded cardinality on mimeType

ontology/action/action.ttl, tests/examples/action_result_PASS.json
This PR removes action:ActionReferencesFacet and moves the
properties of this class into action:Action.
In addition, the second commit addresses the issues with CI passing
upon completion of this change. @ajnelson-nist will need to confirm
that this is a proper method to address this.
References:
[*] [OC-62] (CP-89) Remove ActionReferenceFacet and move properties
into action:Action
=> (CP-89) Move properties from ActionReferencesFacet to Action

ontology/observable/observable.ttl
**Background**
The `uco-observable:CallFacet` has a property `uco-observable:application` that has a cardinality of `1 <-> 1` which is causing issues for an adopting implementation. 
**Proposed Change**
Remove the lower bound to change the cardinality of the `uco-observable:application`  property from `1 <-> 1` to `0 <-> 1` in the `uco-observable:CallFacet`.
**Use Cases**
The use case we're seeing is that some forensic tools find the record of the phone call, but not an associated application and in the interim, we need to make a "dummy" application.
Additional use cases for removing the lower cardinality restriction include devices such as feature phones that don't have a separately defined application (such as Samsung's `com.samsung.android.dialer`).
=> OC-210 Remove Application Lower Cardinality

ontology/observable/observable.ttl
**Background**
The `uco-observable:NoteFacet` has a property `uco-observable:application` that has a cardinality of `1 <-> 1` which is causing issues for an adopting implementation. 
**Proposed Change**
Remove the lower bound to change the cardinality of the `uco-observable:application`  property from `1 <> 1` to `0 <> 1` in the `uco-observable:NoteFacet`.
**Use Cases**
The use case we're seeing is that some forensic tools find the record of the notes, but not an associated application and in the interim, we need to make a "dummy" application.
=> OC-212 Remove NoteFacet:application Cardinality

ontology/observable/observable.ttl
Changed observable:inReplyTo to an owl:DatatypeProperty with an rdfs:range of xsd:string.
This Pull Request resolves all requirements of [Issue 380](https://github.com/ucoProject/UCO/issues/380).
=> Implemented Issue 380

tests/examples/hash_XFAIL_validation.ttl
This Pull Request is a cleanup to side effects from what is currently suspected to have come from either Issue #406 , from an unrealized effect in the release of `rdflib` 6.2.0, or both.  The submitter believes risk from adoption, to UCO and downstream ontologies, is zero.
Somewhere in the chain between core `rdflib`, `pyshacl`, and `rdf-toolkit.jar`, the normalized Turtle content sometimes picks up redundant `rdf:List` artifacts that vary between runs.  The anonymous list cut in this patch has been seen to waver in how much of it is left as a detached blank node, here and in other CASE examples.
The first patch in this PR removes the orphaned list.  Guidance needs to be provided that, as long as this bug in the tool stack persists, the Make-managed generated output should not have it …
=> Cut errant rdf:List artifact

ontology/uco/observable/observable.ttl
Addresses [ONT-469](https://cyberontology.atlassian.net/browse/ONT-469) and matches the proposed example in [CASE Examples!67](https://github.com/casework/CASE-Examples/pull/67) 
Provides objects, facets, and properties to allow representation of cell sites and related metadata.
- Tracking in Jira ticket [OC-258](https://unifiedcyberontology.atlassian.net/browse/OC-258)
=> ONT-469: Cell Site Representation

ontology/uco/identity/identity.ttl, ontology/uco/observable/observable.ttl, ontology/uco/tool/tool.ttl
This Pull Request resolves all requirements of Issue #428 .
=> Issue 428: Remove sh:minCounts to support minimal object definitions

ontology/owl/owl.ttl, tests/examples/owl_axiom_XFAIL_validation.ttl, tests/examples/owl_properties_XFAIL_validation.ttl
This is filed as a bugfix Pull Request due to a discovery made in Issue #457 .
SHACL Specification Section 5.2.1 specifies a "viral" behavior of `sh:declare` throughout an OWL transitive closure.  This patch removes usage of `sh:declare` as a matter of lack of authority for non-UCO prefixes.  It just so happens the only place this was used was in the introduction of the OWL SHACL review mechanisms of Issue 406.
- Tracking in Jira ticket [OC-268](https://unifiedcyberontology.atlassian.net/browse/OC-268)
=> Remove usage of sh:declare

ontology/uco/vocabulary/vocabulary.ttl
The solution of [Issue 435](https://github.com/ucoProject/UCO/issues/435) was known to have an effect on [PR 408](https://github.com/ucoProject/UCO/pull/408).  We had missed doing a catch-up merge after 435's PR was merged prematurely.
This bugfix PR resolves a conflict between the PRs, and should be merged as soon as the CIs in the checklist finish.  Also, should the vote for issue 435 not pass, this PR will need to be reverted.  It will not be necessary to post documentation to the 1.0.0 release page for this PR.
- Tracking in Jira ticket [OC-269](https://unifiedcyberontology.atlassian.net/browse/OC-269)
=> Issue 435 and CP 43: Backport datatype syntax fix to recoverability vocabulary

ontology/uco/core/core.ttl, tests/examples/Makefile, tests/examples/has_facet_inverse_functional_PASS.json, tests/examples/has_facet_inverse_functional_PASS_validation.ttl, tests/examples/has_facet_inverse_functional_XFAIL.json, tests/examples/has_facet_inverse_functional_XFAIL_validation.ttl, tests/examples/test_validation.py
This Pull Request resolves all requirements of Issue #379 .
=> Issue 379: Designate and test core:hasFacet as an inverse-functional property

ontology/uco/observable/observable.ttl
The patch in this PR should have been applied before merging PR #414.  It's not quite clear at the moment how CI missed it.
This is PR 2 of 3 in resolving [Issue 375](https://github.com/ucoProject/UCO/issues/375).
=> Issue 375: Fix CI state with normalization patch

ontology/uco/observable/observable.ttl
This Pull Request resolves remaining requirements of Issue #375 .
=> Issue 375: For EventRecords, rename device property and finish computer property removal

ontology/uco/observable/observable.ttl
Changed Event to EventRecord, and EventFacet to EventRecordFacet.
This Pull Request changes the EventFacet to EventRecordFacet, which resolves ambiguity raised in discussion of Issues #375 and #396 and #401.
=> Issue 416: Change name of Event to EventRecord

ontology/uco/types/types.ttl
This Pull Request will resolve all requirements of [Issue 469](https://github.com/ucoProject/UCO/issues/469).
=> Issue 469: Make ControlledDictionary a subclass of Dictionary

tests/examples/test_validation.py, tests/test_uco_monolithic.py
Addresses errors so that `mypy [--strict]` can run against the `tests/` directory.
- Changed argument type definition
- Added return types
=> MyPy Fixes

ontology/co/co.ttl, ontology/owl/owl.ttl
The SHACL import-review ontologies didn't get `rdfs:label`s assigned
when they were created.  This patch adds them to fit style practice with
other UCO ontology files.
This PR is being submitted as a bugfix with no associated Issue.
=> Add labels to recent ontology files

ontology/uco/master/uco.ttl
This should have happened as part of resolving [Issue 432](https://github.com/ucoProject/UCO/issues/432).
No effects were observed on Make-managed files within UCO.  The effect that will happen in the [CASE website monolithic ontology builds](https://github.com/casework/casework.github.io/tree/master/ontology) is an additional `owl:imports` triple.  The review checklist for this issue is skipped.
=> Issue 432: Add direct import of configuration namespace to uco.ttl

ontology/co/co.ttl, ontology/uco/observable/observable.ttl
This Pull Request resolves the risk-free elements of Issue #488 - fixing typo'd concepts.  In contrast, [PR 489](https://github.com/ucoProject/UCO/pull/489) adds the low-but-not-no risk new unit test.
After appropriate portions of the review checklist pass, this PR can be merged independent of PR 489.
=> Issue 488: Fix typos for upstream design vocabularies

ontology/uco/observable/observable.ttl, tests/examples/Makefile, tests/examples/database_records_PASS.json, tests/examples/database_records_PASS_validation.ttl, tests/examples/database_records_XFAIL.json, tests/examples/database_records_XFAIL_validation.ttl, tests/examples/test_validation.py
Addresses UCO-415 by adding database representation.
=> UCO-415 Database Record Representation

ontology/uco/observable/observable.ttl
Addresses #487
Originally added the `xsd:string` types to the following properties:
- [uco-observable:destinationFlags](https://github.com/ucoProject/UCO/blob/master/ontology/uco/observable/observable.ttl#L10171)
- [uco-observable:byteStringValue](https://github.com/ucoProject/UCO/blob/master/ontology/uco/observable/observable.ttl#L9638)
A follow-on patch revised the added types to be `xsd:hexBinary` for `destinationFlags` (to match `sourceFlags`), and `xsd:base64Binary` for `byteStringValue` (to distinguish from `stringValue`).
=> Issue 487: Property Type Updates

ontology/uco/core/core.ttl
This Pull Request is a bug-fix change proposal, believed to be of low risk to the ontology and its downstream resources.
There is no element named `UcoThing-identifier-shape` in core, nearest match is `UcoThing-identifier-regex-shape` so that is probably intended value.
- Tracking in Jira ticket [OC-286](https://unifiedcyberontology.atlassian.net/browse/OC-286)
=> fix(value): corrected classname reference

ontology/owl/owl.ttl, ontology/uco/core/core.ttl, tests/examples/uco_thing_XFAIL_validation.ttl
This Pull Request resolves all requirements of Issue #513 .
=> Bug fix 513

tests/shapes/examples_uco_qc/co_Collection_core_UcoObject_XFAIL.ttl, tests/shapes/examples_uco_qc/co_Collection_core_UcoObject_XFAIL_validation.ttl, tests/shapes/test_qc_shapes.py, tests/shapes/uco-qc.ttl
This Pull Request resolves backwards-compatible requirements of Issue #509 .
=> Issue 509: Test UCO for disjointedness of core:UcoObject and co:Collection

ontology/uco/observable/observable.ttl, tests/examples/Makefile, tests/examples/observable_creation_time_PASS.json, tests/examples/observable_creation_time_PASS_validation.ttl, tests/examples/test_validation.py
This Pull Request is part of the resolution of Issue #508 .
=> Issue 508: Deprecate observable:creationTime, replacing with observableCreatedTime

ontology/uco/observable/observable.ttl
Removes the [`sh:maxCount`](https://github.com/ucoProject/UCO/blob/master/ontology/uco/observable/observable.ttl#L4481) from the `observable:IMEI` property of the `observable:MobileDeviceFacet`. 
This Pull Request resolves all requirements of #521 .
=> Issue 521: Unrestrict Cardinality IMEI

ontology/uco/types/types.ttl, ontology/uco/vocabulary/vocabulary.ttl, tests/examples/hash_XFAIL_validation.ttl, tests/test_uco_monolithic.py
This Pull Request resolves all requirements of Issue #526
=> Issue 526: HashNameVocab SHA3 Support

tests/test_uco_monolithic.py
[PR 527](https://github.com/ucoProject/UCO/pull/527) stumbled on a code synchronization issue that we'd left a unit test to catch, back in [Issue 435](https://github.com/ucoProject/UCO/issues/435).  On reviewing the debug output against a freshly encountered error, the original implementer (myself) deems it ...
```
test_uco_monolithic.py:232: AssertionError
-------------------- Captured log call --------------------
DEBUG    root:test_uco_monolithic.py:224 Match
DEBUG    root:test_uco_monolithic.py:224 Match
DEBUG    root:test_uco_monolithic.py:224 Match
[...snip...]
DEBUG    root:test_uco_monolithic.py:224 Match
DEBUG    root:test_uco_monolithic.py:224 Match
DEBUG    root:test_uco_monolithic.py:226 n2ecb5139feab4fe88096d056f9ba80cab1564
DEBUG    root:test_uco_monolithic.py:227 …
```
=> Clarify synchronization test output

ontology/uco/observable/observable.ttl, tests/examples/Makefile, tests/examples/file_url_PASS.json, tests/examples/file_url_PASS_validation.ttl, tests/examples/test_validation.py
This Pull Request resolves backwards-compatible requirements of Issue #536 .
=> Issue 536: Declare and warn of observable:File and :URL disjointedness

ontology/uco/core/core.ttl
This Pull Request resolves all requirements of Issue #541 .
=> Issue 541: Add Event

ontology/uco/observable/observable.ttl
This Pull Request resolves all requirements of Issue #543 .
=> Issue 543: Designate ObservablePattern a subclass of Pattern, adding namespace import

ontology/owl/owl.ttl, tests/examples/rdf_list_PASS.json, tests/examples/rdf_list_XFAIL.json, tests/examples/rdf_list_XFAIL_validation.ttl
This Pull Request resolves all requirements of Issue #571 .
=> Issue 571: Reduce UCO OWL RDF List review scope to OWL Sequences

ontology/owl/owl.ttl
This Pull Request resolves all requirements of Issue #584 .
=> Issue 584: Replace errant reference to non-existent concept owl:Datatype

ontology/uco/observable/observable.ttl
This Pull Request resolves all backwards-compatible requirements of Issue #573 .
=> Issue 573: Warn if target or source on an ObservableRelationship are not Observables

ontology/owl/owl.ttl, ontology/uco/pattern/pattern.ttl
This Pull Request resolves all requirements of Issue #562 .
=> Issue 562: Revise pattern:patternExpression to be object property, and test for error form

ontology/uco/core/core.ttl, ontology/uco/types/types.ttl, tests/examples/Makefile, tests/examples/disjointedness_PASS.json, tests/examples/disjointedness_PASS_validation.ttl, tests/examples/test_validation.py
This Pull Request resolves all backwards-compatible requirements of Issue #586 .
=> Issue 586: Warn of prior disjointedness declarations in `core:` and `types:`

ontology/uco/observable/observable.ttl, tests/examples/Makefile, tests/examples/alternate_data_stream_PASS.json, tests/examples/alternate_data_stream_PASS_validation.ttl, tests/examples/test_validation.py
This Pull Request resolves all backwards-compatible requirements of Issue #590 .
=> Issue 590: Warn if an AlternateDataStream instance is not also a FileSystemObject

ontology/uco/observable/observable.ttl, tests/examples/alternate_data_stream_PASS.json, tests/examples/alternate_data_stream_PASS_validation.ttl, tests/examples/test_validation.py
This Pull Request resolves all backwards-incompatible requirements of Issue #590 .
=> Issue 590: Change AlternateDataStream parent class to FileSystemObject

ontology/uco/types/types.ttl, tests/examples/Makefile, tests/examples/README.md, tests/examples/dictionary_PASS.json, tests/examples/dictionary_PASS_validation.ttl, tests/examples/dictionary_XFAIL.json, tests/examples/dictionary_XFAIL_validation.ttl, tests/examples/test_validation.py
This Pull Request will resolve all requirements of Issue #602 , as updated 2024-06-04.
This PR is built atop [PR 603](https://github.com/ucoProject/UCO/pull/603)'s current state.  If no updates are made to 603, merging this PR will close 603 as well.
=> Issue 602: Add review mechanisms for key-uniqueness in types:Dictionary

ontology/uco/types/types.ttl, tests/examples/Makefile, tests/examples/dictionary_PASS.json, tests/examples/dictionary_PASS_validation.ttl, tests/examples/test_validation.py
This Pull Request will resolve all requirements of Issue #602 .
=> Issue 602: Warn about key-uniqueness enforcement to types:Dictionary

ontology/uco/core/core.ttl, ontology/uco/vocabulary/vocabulary.ttl, tests/examples/Makefile, tests/examples/object_status_PASS.json, tests/examples/object_status_PASS_validation.ttl, tests/examples/object_status_XFAIL.json, tests/examples/object_status_XFAIL_validation.ttl, tests/examples/test_validation.py
This Pull Request resolves all requirements of Issue #549 .
=> Issue 549: Add objectStatus

ontology/uco/core/core.ttl, ontology/uco/vocabulary/vocabulary.ttl
This Pull Request resolves all requirements of Issue #593 .
=> Issue 593: Remove owl:onDatatype from vocabulary definitions

ontology/uco/observable/observable.ttl
This pull request finishes resolving backwards-incompatible requirements of Issue #612 .
When implementing PR #621 , a snippet of temporary code that was supposed to be deleted ended up restored.  This PR re-does the deletion.
=> Issue 612: Remove temporary review shape

tests/examples/co_XFAIL_validation.ttl, tests/examples/configuration_setting_XFAIL_validation.ttl, tests/examples/database_records_XFAIL_validation.ttl, tests/examples/hash_XFAIL_validation.ttl, tests/examples/object_status_XFAIL_validation.ttl, tests/examples/rdf_list_XFAIL_validation.ttl, tests/examples/thread_XFAIL_validation.ttl
This is a maintenance Pull Request, incorporating no new features.  Make-managed files that demonstrate validation results are regenerated.  Recent updates to the SHACL validation tool include adjusted result message template strings, so all test results going forward will reflect new templating.
Once CI passes, this PR can be merged.
=> Regenerate example-validation files

ontology/uco/action/action.ttl, ontology/uco/core/core.ttl, ontology/uco/observable/observable.ttl, ontology/uco/types/types.ttl, ontology/uco/vocabulary/vocabulary.ttl, tests/examples/action_inheritance_PASS.json, tests/examples/action_inheritance_PASS_validation.ttl, tests/examples/action_inheritance_XFAIL_validation.ttl, tests/examples/hash_PASS.json, tests/examples/hash_PASS_validation.ttl, tests/examples/hash_XFAIL.json, tests/examples/hash_XFAIL_validation.ttl, tests/examples/object_status_PASS.json, tests/examples/object_status_XFAIL_validation.ttl, tests/examples/test_validation.py, tests/test_uco_monolithic.py
This Pull Request will resolve all backwards-compatible requirements of #629 .
=> Issue 629: Revise vocabulary pattern

ontology/uco/action/action.ttl, ontology/uco/observable/observable.ttl, ontology/uco/types/types.ttl, tests/examples/hash_PASS.json, tests/examples/hash_PASS_validation.ttl, tests/examples/hash_XFAIL.json, tests/examples/hash_XFAIL_validation.ttl, tests/examples/test_validation.py
This Pull Request resolves all backwards-incompatible requirements of Issue #629 .
=> Issue 629: Enforce vocabulary pattern revision for UCO 2.0.0
