- uco-observable/observable.ttl
Fixes #86 #87
Although the changes to observable.ttl were limited. The noramlization process created a huge non-substantial change and diff. I will keep learning to minimize this hassle.
Keeping the PR's and Commits focused will help.
> Fix commits 86 87

- uco-core/core.ttl
- uco-observable/observable.ttl
Modified core:name to be DatatypeProperty rather than ObjectProperty.
Modified all restrictions on core:name to utilize appropriate owl:onClass of xsd:string
Modified all uses of observable:name to utilize core:name
Removed observable:name
> Modifications to address issue #99

- uco-investigation/investigation.ttl
Modified subClass of Authorization from core:Facet to be core:UcoObject
Added investigation:relevantAuthorization ObjectProperty with domain of investigation:Investigation and range of investigation:Authorization and no cardinality restriction defined as it should have 0..n cardinality.
> Modifications to address issue #100

- uco-marking/marking.ttl
Added LicenseMarking class and its accompanying marking:license property
Added ReleaseToMarking class and its accompanying marking:authorizedIdentities property
Added StatementMarking class and its accompanying marking:statement property
Added TermsOfUseMarking class and its accompanying marking:termsOfUse property
> Modifications to address issue #98

- uco-core/core.ttl
fixes #115 
I removed a duplicate rdfs:range from line 283.
I changed the @en-US to @en  on line 13 
removed a duplicate semicolon from line 291
> removed duplicate range statement in line 283

- uco-marking/marking.ttl
this was just an imbalance in quotation marks.
> Correcting imbalances in comment quotations. fixes #118

- uco-observable/observable.ttl
This addresses [Issue 122](https://github.com/ucoProject/UCO/issues/122).
> Correct rdfs:label of observable definition

- catalog-v001.xml
- uco-action/action.ttl
- uco-core/core.ttl
- uco-identity/identity.ttl
- uco-investigation/investigation.ttl
- uco-location/location.ttl
- uco-marking/marking.ttl
- uco-master/uco.ttl
- uco-observable/observable.ttl
- uco-pattern/pattern.ttl
- uco-role/role.ttl
- uco-time/time.ttl
- uco-tool/tool.ttl
- uco-types/types.ttl
- uco-victim/victim.ttl
Modified all namespace URI base values from "http://unifiedcyberontology.org/" to "https://unifiedcyberontology.org/ontology/uco/"
> Modifications to address issue #103

- uco-marking/marking.ttl
- uco-observable/observable.ttl
> Modifications to fix issues 83 & 128

- uco-identity/identity.ttl
Changed identity:Relationship to be identity:RelatedIdentity
> Modifications to address issue #41

- uco-core/core.ttl
Modified range of core:tag from core:Annotation to core:UcoObject such that all objects can now have tags
> Modifications to address issue #46

- uco-observable/observable.ttl
Fixed comments for :creator and :messageId
> Modifications to address issue #131

- uco-core/core.ttl
REmoved HasIdentity, HasLocation & RelatedIdentity classes
> Modifications to address issue #42

- uco-observable/observable.ttl
This addresses [Issue 138](https://github.com/ucoProject/UCO/issues/138).
> Correct typo "PDFFIle"

- uco-observable/observable.ttl
This addresses [Issue 140](https://github.com/ucoProject/UCO/issues/140).
> Correct documentation typo "sSpecifies"

- uco-observable/observable.ttl
This addresses [Issue 143](https://github.com/ucoProject/UCO/issues/143).
> Correct casing of "picturetype"

- uco-observable/observable-da.ttl
- uco-observable/observable.ttl
Updated observable:omment to observable:taskComment
> Issue 137 erh

- uco-master/uco.ttl
Added a missing time.ttl import to the master.ttl (uco-master).
> Issue 148 erh

- uco-core/core-da.ttl
- uco-core/core.ttl
This feature branch is implementation complete and has been approved by OC vote 11/16/20
> Modified core:facets to core:hasFacet in support of CP12

- uco-observable/observable-da.ttl
- uco-observable/observable.ttl
This feature branch is implementation complete and has been approved by OC vote 11/16/20
> Feature cp11

- uco-core/core.ttl
This applies rdf-toolkit's formatting per the CASE CONTRIBUTE.md
instructions.
References:
* [OC-28] (CP-9) Refactor ExternalReference
> Normalize syntax

- uco-observable/observable.ttl
> Feature cp 8 quickfix

- uco-observable/observable.ttl
Modified cardinality of observable:hasChanged on observable:ObservableObject
> Implements BugFix-CP-59

- ontology/observable/observable.ttl
Added "rdfs:range xsd:dateTime" to observable:lastTimeContacted.
> Implemented Bug Fix for CP-97

- ontology/observable/observable.ttl
> Revert "Allow unbounded cardinality on mimeType"

- uco-vocabulary/vocabulary.ttl
I went over all datatypes and fixed all copy-paste type errors that I identified.
> Updated all vocabulary namespaces to local (OC-132)

- ontology/observable/observable.ttl
This supersedes [PR 322](https://github.com/ucoProject/UCO/pull/322).
> [OC-122] Add Android device facet v2

- ontology/observable/observable.ttl
For more details look at #329  and [OC-203](https://unifiedcyberontology.atlassian.net/browse/OC-203)
> OC-203 - Fix the missing field for `lastTimeContacted`

- ontology/observable/observable.ttl
This re-applies [PR 342](https://github.com/ucoProject/UCO/pull/342).
> Allow unbounded cardinality on mimeType

- CONTRIBUTE.md
This pull request follows an alternative review procedure, requiring approval from the Technical Steering Committee instead of the Ontology Committee. It will not trigger requiring a release.
> Start CONTRIBUTE.md with development-state testing link

- CONTRIBUTE.md
This pull request follows an alternative review procedure, requiring approval from the Technical Steering Committee instead of the Ontology Committee. It will not trigger requiring a release.
> Fix website link in CONTRIBUTE.md

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/change-request.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/question.md
- .github/pull_request_template.md
This pull request follows an alternative review procedure, requiring approval from the Technical Steering Committee instead of the Ontology Committee. It will not trigger requiring a release.
> Add issue templates

- ontology/observable/observable.ttl
This pull request resolves Requirement 1 of Issue #357 .
> Change rdfs:comment in sh:PropertyShape to sh:description

- ontology/observable/observable.ttl
This pull request resolves all requirements of Issue #351 .
> (Issue 351) Convert observable:userName to Datatype property

- ontology/observable/observable.ttl
This Pull Request resolves all requirements of [Issue 383](https://github.com/ucoProject/UCO/issues/383).
> Expand cardinality of isMimeEncoded and isMultipart to 0..1

- ontology/core/core.ttl
This Pull Request resolves all ontology requirements of Issue #378 . For the documentation requirement, refer to [ucoproject.github.io's PR 41](https://github.com/ucoProject/ucoproject.github.io/pull/41)
> Solution implementation to Cp 378

- README.md
- ontology/master/uco.ttl
(To be applied after merging [PR 402](https://github.com/ucoProject/UCO/pull/402).)
> Release 0.9.0

- ontology/observable/observable.ttl
This Pull Request resolves all requirements of [Issue 391](https://github.com/ucoProject/UCO/issues/391).
> Rename observable:Thread to observable:ProcessThread

- ontology/observable/observable.ttl
This Pull Request resolves all requirements of Issue #396.
> 396 Event Facet Duration

- ontology/uco/observable/observable.ttl
This Pull Request resolves all requirements of Issue #421 .
> Issue 421: Add PDF time properties

- ontology/uco/observable/observable.ttl
This Pull Request resolves all requirements of Issue #443  .
changed submit to develop branch rather than master
> Issue 443: Add observable:mutexName

- ontology/uco/observable/observable.ttl
> Removed MSISDN from observable:MobileDeviceFacet

- ontology/uco/tool/tool.ttl
- tests/examples/Makefile
- tests/examples/configuration_setting_PASS.json
- tests/examples/configuration_setting_PASS_validation.ttl
- tests/examples/configuration_setting_XFAIL.json
- tests/examples/configuration_setting_XFAIL_validation.ttl
- tests/examples/test_validation.py
This Pull Request resolves all requirements of Issue #405 .
> Issue 405: Add ConfiguredTool; expand configuration to string-thing-nothing

- Makefile
One further patch will be added to this PR after the Requirements Review vote, to update the pointer to a newly created release.
This Pull Request will resolve all requirements of [Issue 417](https://github.com/ucoProject/UCO/issues/417).
> Bump CASE SHACL Inheritance Reviewer (SHIR) Utility

- ontology/uco/core/core.ttl
- ontology/uco/master/uco.ttl
This Pull Request resolves all requirements of Issue #431 .
> Issue 431: Remove core:id

- ontology/uco/core/core.ttl
This Pull Request resolves all requirements of Issue #433 .
> Issue 433: Remove core:type

- ontology/owl/owl.ttl
This Pull Request resolves all requirements of Issue #499 .
> Correct SHACL-SPARQL syntax of value selector

- ontology/owl/owl.ttl
- tests/shapes/examples_uco_owl/owl_shacl_paths_PASS.ttl
- tests/shapes/examples_uco_owl/owl_shacl_paths_PASS_validation.ttl
- tests/shapes/test_qc_shapes.py
This Pull Request is a bug-fix change proposal, believed to be of low risk to the ontology and its downstream resources.
Patch 1 is expected to fail CI.  Patches 2 and 3 are expected to pass.
> Issue 502: Adjust SHACL-SPARQL sequence path queries to search for end

- tests/Makefile
- tests/thing.ttl
This Pull Request resolves all requirements of Issue #504 .
> Issue 504: Test monolithic build with SHACL-SHACL

- README.md
- ontology/co/co.ttl
- ontology/owl/owl.ttl
- ontology/uco/action/action.ttl
- ontology/uco/analysis/analysis.ttl
- ontology/uco/configuration/configuration.ttl
- ontology/uco/core/core.ttl
- ontology/uco/identity/identity.ttl
- ontology/uco/location/location.ttl
- ontology/uco/marking/marking.ttl
- ontology/uco/master/uco.ttl
- ontology/uco/observable/observable.ttl
- ontology/uco/pattern/pattern.ttl
- ontology/uco/role/role.ttl
- ontology/uco/time/time.ttl
- ontology/uco/tool/tool.ttl
- ontology/uco/types/types.ttl
- ontology/uco/victim/victim.ttl
- ontology/uco/vocabulary/vocabulary.ttl
> Release 1.1.0

- ontology/owl/owl.ttl
- ontology/uco/core/core.ttl
- ontology/uco/observable/observable.ttl
- tests/examples/uco_thing_XFAIL_validation.ttl
This is part of resolving #501 .
> Issue 501: Catch `develop-2.0.0` up to `develop`

- .github/ISSUE_TEMPLATE/change-request.md
This Pull Request updates GitHub templating.  As a matter of GitHub interface programming, committee review is not required.
> Update change request template

- ontology/uco/action/action.ttl
This Pull Request implements a bug-fix change proposal, believed to be of low risk to the ontology and its downstream resources.  It resolves all requirements of Issue #556 .
> Issue 556: Designate ActionLifecycle a subclass of ActionPattern

- ontology/uco/observable/observable.ttl
This Pull Request resolves all backwards-incompatible requirements of Issue #573 .
> Issue 573: Require target or source on an ObservableRelationship be Observables

- ontology/uco/core/core.ttl
- tests/examples/disjointedness_PASS_validation.ttl
This Pull Request is a follow-on to [PR 587](https://github.com/ucoProject/UCO/pull/587).  No further committee action is needed.
> Issue 586: Fix typo

- .github/workflows/ci.yml
This is a maintenance Pull Request, incorporating no new features.  Once CI passes, this PR can be merged.
> Bump GitHub Action versions

- .github/workflows/ci.yml
- Makefile
- lib/Makefile
- ontology/Makefile
- ontology/co/Makefile
- ontology/owl/Makefile
- ontology/uco/Makefile
- src/create-catalog-v001.xml.py
- src/populate_node_kind.py
- src/review.mk
- tests/Makefile
- tests/dependencies/Makefile
- tests/examples/Makefile
- tests/examples/test_validation.py
- tests/shapes/Makefile
- tests/shapes/examples_uco_owl/Makefile
- tests/shapes/examples_uco_qc/Makefile
- tests/shapes/test_qc_shapes.py
- tests/test_uco_monolithic.py
This is a maintenance Pull Request, incorporating no new features.  This PR applies updates done for NIST licensing text throughout the CDO ecosystem.
Once CI passes, this PR can be merged.
> Update NIST licensing text

- ontology/uco/observable/observable.ttl
- tests/examples/Makefile
- tests/examples/operating_system_PASS.json
- tests/examples/operating_system_PASS_validation.ttl
- tests/examples/test_validation.py
This Pull Request resolves all backwards-compatible requirements of Issue #632 .
> Issue 632: Prepare OperatingSystem to become a subclass of Software

- ontology/uco/core/core.ttl
This Pull Request is a bug-fix change proposal, believed to be of low risk to the ontology and its downstream resources.
This PR catches a typo made from copy-pasting some Turtle for syntax, while implementing [Issue 563](https://github.com/ucoProject/UCO/issues/563).
> Issue 563: Fix copy-paste error
